NumPy (Numerical Python) is a powerful Python library used for numerical computing. It provides support for:

Multi-dimensional arrays (ndarray)
Mathematical operations on arrays
Linear algebra
Statistical functions
Random number generation
Fast execution compared to Python lists

In [1]:
import numpy as np

arr1= np.array([1,2,3,4])
print(arr1)


[1 2 3 4]


In [2]:
print(np.__version__)

2.4.6


In [4]:
# 2d arrays
arr2 = np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [5]:
lst = [1,2,3,4,5]
print("this is my list", lst)
print("type of my list",type(lst))
print("list is converted into array")
arr=np.array(lst)
print("this is array", arr)
print("type of my array", type(arr))


this is my list [1, 2, 3, 4, 5]
type of my list <class 'list'>
list is converted into array
this is array [1 2 3 4 5]
type of my array <class 'numpy.ndarray'>


In [6]:
arr = np.zeros(50)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [7]:
arr = np.ones(20)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
arr= np.zeros([5,10])
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
arr = np.arange(60)
print(arr)
arr=arr.reshape(12,5) # converting of 1d array into 2d array
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [ ]:
# array attributes or function 
arr = np.array([[1,3],[5,3]])
print(arr)
print(arr.shape)  
print(arr.ndim)    
print(arr.size)    
print(arr.dtype)

(2, 2)
2
4
int64


In [17]:
#slicing in fucking array
arr[0:5]

array([[1, 3],
       [5, 3]])

In [19]:
#indexing 
arr[0],arr[1]

(array([1, 3]), array([5, 3]))

In [22]:
arr[::,-1]

array([3, 3])